version: "3.8"
services:
  app:
    container_name: suivi-bourse-app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data:/data
    restart: unless-stopped
    environment: 
      - "INFLUXDB_DATABASE=${INFLUXDB_DATABASE}"
      - "INFLUXDB_PORT=${INFLUXDB_PORT}"
      - "INFLUXDB_HOST=${INFLUXDB_HOST}"
  influxdb:
    container_name: suivi-bourse-influxdb
    image: "influxdb:1.8"
    ports:
      - "${INFLUXDB_PORT}:8086"
    environment:
      - "INFLUXDB_DB=${INFLUXDB_DATABASE}"
  grafana:
    container_name: suivi-bourse-grafana
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_provisioning:/etc/grafana/provisioning
