version: "3.8"
services:
  app:
    container_name: suivi-bourse-app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data:/data
    restart: unless-stopped
  influxdb:
    container_name: suivi-bourse-influxdb
    image: "influxdb:1.8"
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=bourse
  grafana:
    container_name: suivi-bourse-grafana
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_provisioning:/etc/grafana/provisioning
